version: "3"
services:
  backend:
    image: gcr.io/welpdev/welp
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    image: mysql:5.7.14
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    links:
      - "db:db2"
